# Generated by Django 5.2.9 on 2025-12-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="favorite",
            new_name="favorites_f_asset_i_f28939_idx",
            old_name="favorites_f_asset_6bdfcc_idx",
        ),
    ]
