# Generated by Django 5.2.9 on 2025-12-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_asse_status_3b4017_idx",
            old_name="assets_asse_status_7fb64f_idx",
        ),
    ]
