# Generated by Django 5.2.9 on 2025-12-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="portfolioitem",
            new_name="portfolio_p_asset_i_b4a56f_idx",
            old_name="portfolio_por_asset_52d3de_idx",
        ),
    ]
